nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With','Access-Control-Allow-Origin']
        expose_headers: ['Authorization', 'Content-Type','Access-Control-Allow-Origin']
        max_age: 3600
    paths:
        '^/': null
